"""gig income, vehicles, employees, salary slips, tax docs

Revision ID: 525c59bcf550
Revises: a9e5e7d2d9d8
Create Date: 2026-09-30 19:25:31.380780
"""
from alembic import op
import sqlalchemy as sa
import firmabok.core.db as app_db


revision = '525c59bcf550'
down_revision = 'a9e5e7d2d9d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('personnummer', sa.String(length=24), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('employment_type', sa.String(length=16), nullable=False),
    sa.Column('monthly_salary', app_db.Money(2), nullable=False),
    sa.Column('hourly_rate', app_db.Money(2), nullable=False),
    sa.Column('revenue_pct', app_db.Money(2), nullable=False),
    sa.Column('contract_terms', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('tax_table_note', sa.String(length=200), nullable=False),
    sa.Column('bank_account', sa.String(length=64), nullable=False),
    sa.Column('ag_rate_override', app_db.Money(2), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gig_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('salary_slip_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_year', sa.Integer(), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_year', name='uq_salary_slip_series_year')
    )
    op.create_table('tax_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('period_text', sa.String(length=64), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_documents_doc_type'), ['doc_type'], unique=False)

    op.create_table('tax_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipal_tax_pct', app_db.Money(2), nullable=False),
    sa.Column('church_pct', app_db.Money(2), nullable=False),
    sa.Column('burial_pct', app_db.Money(2), nullable=False),
    sa.Column('extra_deduction', app_db.Money(2), nullable=False),
    sa.Column('ag_rate_default', app_db.Money(2), nullable=False),
    sa.Column('youth_enabled', sa.Boolean(), nullable=False),
    sa.Column('youth_rate', app_db.Money(2), nullable=False),
    sa.Column('youth_ceiling', app_db.Money(2), nullable=False),
    sa.Column('youth_birth_from', sa.Integer(), nullable=False),
    sa.Column('youth_birth_to', sa.Integer(), nullable=False),
    sa.Column('youth_valid_from', sa.Date(), nullable=False),
    sa.Column('youth_valid_to', sa.Date(), nullable=False),
    sa.Column('mileage_rate', app_db.Money(2), nullable=True),
    sa.Column('vat_deadline_day', sa.Integer(), nullable=False),
    sa.Column('vat_deadline_month_offset', sa.Integer(), nullable=False),
    sa.Column('source_note', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('reg_no', sa.String(length=24), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('year_model', sa.Integer(), nullable=True),
    sa.Column('assigned_employee_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_assigned_employee_id'), ['assigned_employee_id'], unique=False)

    op.create_table('salary_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('series_year', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('gross', app_db.Money(2), nullable=False),
    sa.Column('employer_contributions', app_db.Money(2), nullable=False),
    sa.Column('a_tax', app_db.Money(2), nullable=False),
    sa.Column('net', app_db.Money(2), nullable=False),
    sa.Column('hours', app_db.Money(2), nullable=True),
    sa.Column('revenue_base', app_db.Money(2), nullable=True),
    sa.Column('lines', sa.Text(), nullable=False),
    sa.Column('ag_rate_used', app_db.Money(2), nullable=False),
    sa.Column('youth_reduction', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('salary_slips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_slips_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_slips_series_year'), ['series_year'], unique=False)

    op.add_column('expenses', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('mileage', app_db.Money(2), nullable=True))
    op.create_index('ix_expenses_employee_id', 'expenses', ['employee_id'], unique=False)
    op.create_index('ix_expenses_vehicle_id', 'expenses', ['vehicle_id'], unique=False)

    op.add_column('income_entries', sa.Column('source_type', sa.String(length=10), nullable=False, server_default='direct'))
    op.add_column('income_entries', sa.Column('platform_name', sa.String(length=120), nullable=False, server_default=''))
    op.create_index('ix_income_entries_source_type', 'income_entries', ['source_type'], unique=False)
    op.create_index('ix_income_entries_platform_name', 'income_entries', ['platform_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_income_entries_platform_name', table_name='income_entries')
    op.drop_index('ix_income_entries_source_type', table_name='income_entries')
    op.drop_column('income_entries', 'platform_name')
    op.drop_column('income_entries', 'source_type')
    op.drop_index('ix_expenses_vehicle_id', table_name='expenses')
    op.drop_index('ix_expenses_employee_id', table_name='expenses')
    op.drop_column('expenses', 'mileage')
    op.drop_column('expenses', 'employee_id')
    op.drop_column('expenses', 'vehicle_id')
    op.drop_index('ix_salary_slips_series_year', table_name='salary_slips')
    op.drop_index('ix_salary_slips_employee_id', table_name='salary_slips')
    op.drop_table('salary_slips')
    op.drop_index('ix_vehicles_assigned_employee_id', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('tax_parameters')
    op.drop_index('ix_tax_documents_doc_type', table_name='tax_documents')
    op.drop_table('tax_documents')
    op.drop_table('salary_slip_series')
    op.drop_table('gig_platforms')
    op.drop_table('employees')
