"""payment display, ocr toggle, account number

Revision ID: a9e5e7d2d9d8
Revises: a9dc2d5c3468
Create Date: 2026-09-29 20:11:08.781173
"""
from alembic import op
import sqlalchemy as sa
import firmabok.core.db as app_db  # noqa: F401


revision = 'a9e5e7d2d9d8'
down_revision = 'a9dc2d5c3468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('payment_display', sa.String(length=16), nullable=False, server_default='bankgiro'))
        batch_op.add_column(sa.Column('invoice_show_ocr', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.drop_column('invoice_show_ocr')
        batch_op.drop_column('payment_display')
        batch_op.drop_column('bank_account_number')

    # ### end Alembic commands ###
