"""initial schema

Revision ID: 6f0706aa6a01
Revises: 
Create Date: 2026-09-29 16:17:44.876523
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '6f0706aa6a01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('org_nr', sa.String(length=16), nullable=False),
    sa.Column('vat_number', sa.String(length=16), nullable=False),
    sa.Column('f_skatt_registered', sa.Boolean(), nullable=False),
    sa.Column('f_skatt_text', sa.String(length=200), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('bankgiro', sa.String(length=32), nullable=False),
    sa.Column('plusgiro', sa.String(length=32), nullable=False),
    sa.Column('iban', sa.String(length=64), nullable=False),
    sa.Column('bic', sa.String(length=16), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('late_interest_rate', app.db.Money(2), nullable=False),
    sa.Column('invoice_notes', sa.Text(), nullable=False),
    sa.Column('invoice_number_prefix', sa.String(length=16), nullable=False),
    sa.Column('invoice_number_digits', sa.Integer(), nullable=False),
    sa.Column('invoice_number_start', sa.Integer(), nullable=False),
    sa.Column('default_city_for_dates', sa.String(length=100), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('vat_period', sa.String(length=10), nullable=False),
    sa.Column('simplified_vat_mode', sa.Boolean(), nullable=False),
    sa.Column('default_vat_rate', app.db.Money(2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_business', sa.Boolean(), nullable=False),
    sa.Column('org_nr', sa.String(length=24), nullable=False),
    sa.Column('vat_number', sa.String(length=24), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_customer_no'), ['customer_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)

    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bas_account_hint', sa.String(length=16), nullable=False),
    sa.Column('default_vat_code', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invoice_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_year', sa.Integer(), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_year', name='uq_invoice_series_year')
    )
    op.create_table('owner_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_date', sa.Date(), nullable=False),
    sa.Column('tx_type', sa.String(length=16), nullable=False),
    sa.Column('amount', app.db.Money(2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_transactions_tx_date'), ['tx_date'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('password_salt', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vat_rates',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label_sv', sa.String(length=200), nullable=False),
    sa.Column('percent', app.db.Money(2), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('skv_boxes', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('vat_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_kind', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('boxes', sa.Text(), nullable=False),
    sa.Column('output_vat', app.db.Money(2), nullable=False),
    sa.Column('input_vat', app.db.Money(2), nullable=False),
    sa.Column('net_vat', app.db.Money(2), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_kind', 'fiscal_year', 'period_number', name='uq_vat_report_period')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('vat_code', sa.String(length=32), nullable=False),
    sa.Column('net_amount', app.db.Money(2), nullable=False),
    sa.Column('vat_rate', app.db.Money(2), nullable=False),
    sa.Column('vat_amount', app.db.Money(2), nullable=False),
    sa.Column('gross_amount', app.db.Money(2), nullable=False),
    sa.Column('deductible_vat', app.db.Money(2), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=False),
    sa.Column('receipt_path', sa.String(length=500), nullable=False),
    sa.Column('receipt_original_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category_name'), ['category_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_supplier'), ['supplier'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_vat_code'), ['vat_code'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('series_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_credit_note', sa.Boolean(), nullable=False),
    sa.Column('credit_note_for_id', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_snapshot', sa.Text(), nullable=False),
    sa.Column('ocr', sa.String(length=32), nullable=False),
    sa.Column('our_reference', sa.String(length=120), nullable=False),
    sa.Column('customer_reference', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('net_total', app.db.Money(2), nullable=False),
    sa.Column('vat_total', app.db.Money(2), nullable=False),
    sa.Column('gross_total', app.db.Money(2), nullable=False),
    sa.Column('amount_paid', app.db.Money(2), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_note_for_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_series_year'), ['series_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    op.create_table('user_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flash', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('income_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('vat_code', sa.String(length=32), nullable=False),
    sa.Column('net_amount', app.db.Money(2), nullable=False),
    sa.Column('vat_rate', app.db.Money(2), nullable=False),
    sa.Column('vat_amount', app.db.Money(2), nullable=False),
    sa.Column('gross_amount', app.db.Money(2), nullable=False),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('invoice_ref', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_entries_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_entries_vat_code'), ['vat_code'], unique=False)

    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', app.db.Money(3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('unit_price', app.db.Money(2), nullable=False),
    sa.Column('vat_code', sa.String(length=32), nullable=False),
    sa.Column('vat_rate', app.db.Money(2), nullable=False),
    sa.Column('line_net', app.db.Money(2), nullable=False),
    sa.Column('line_vat', app.db.Money(2), nullable=False),
    sa.Column('line_gross', app.db.Money(2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_lines_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_lines_invoice_id'))

    op.drop_table('invoice_lines')
    with op.batch_alter_table('income_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_entries_vat_code'))
        batch_op.drop_index(batch_op.f('ix_income_entries_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_income_entries_entry_date'))

    op.drop_table('income_entries')
    op.drop_table('user_sessions')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_series_year'))
        batch_op.drop_index(batch_op.f('ix_invoices_number'))

    op.drop_table('invoices')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_vat_code'))
        batch_op.drop_index(batch_op.f('ix_expenses_supplier'))
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_category_name'))

    op.drop_table('expenses')
    op.drop_table('vat_reports')
    op.drop_table('vat_rates')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('settings')
    with op.batch_alter_table('owner_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_transactions_tx_date'))

    op.drop_table('owner_transactions')
    op.drop_table('invoice_series')
    op.drop_table('expense_categories')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_no'))

    op.drop_table('customers')
    op.drop_table('company_profile')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))

    op.drop_table('audit_log')
    op.drop_table('attachments')
    # ### end Alembic commands ###
